// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC795neOfs9pZebT3NOWy-oD6jjOXHM9sw',
    appId: '1:106277281333:web:a17877d926fa52791e9b7c',
    messagingSenderId: '106277281333',
    projectId: 'watering-6ff52',
    authDomain: 'watering-6ff52.firebaseapp.com',
    databaseURL: 'https://watering-6ff52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watering-6ff52.firebasestorage.app',
    measurementId: 'G-FCTJY7XFYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnLd32cGr2rFsejA0nwWHwGuhFAe4BRYI',
    appId: '1:106277281333:android:02691d376a6b2fa71e9b7c',
    messagingSenderId: '106277281333',
    projectId: 'watering-6ff52',
    databaseURL: 'https://watering-6ff52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watering-6ff52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDj3es5mEMYRWWGSTy7ckEzRBAKaIEKPw',
    appId: '1:106277281333:ios:acb87de6abd36eef1e9b7c',
    messagingSenderId: '106277281333',
    projectId: 'watering-6ff52',
    databaseURL: 'https://watering-6ff52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watering-6ff52.firebasestorage.app',
    iosBundleId: 'com.example.wateringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDj3es5mEMYRWWGSTy7ckEzRBAKaIEKPw',
    appId: '1:106277281333:ios:acb87de6abd36eef1e9b7c',
    messagingSenderId: '106277281333',
    projectId: 'watering-6ff52',
    databaseURL: 'https://watering-6ff52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watering-6ff52.firebasestorage.app',
    iosBundleId: 'com.example.wateringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC795neOfs9pZebT3NOWy-oD6jjOXHM9sw',
    appId: '1:106277281333:web:8c07194f12618ad01e9b7c',
    messagingSenderId: '106277281333',
    projectId: 'watering-6ff52',
    authDomain: 'watering-6ff52.firebaseapp.com',
    databaseURL: 'https://watering-6ff52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watering-6ff52.firebasestorage.app',
    measurementId: 'G-PXJ0DQE2H1',
  );

}